#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

init(){
    lein garden once
    lein do clean, figwheel
}

"$@"
