#!/bin/bash

clean(){
    rm -rf .shadow-cljs node_modules .cpcache
}

dev(){
    clj -A:fig
}

help(){
    clj -A:fig -h
}

clpth(){
    clj -Spath |  sed -e 's/:/\'$'\n/g' | head -n 5
}

dev(){
    clojure -m figwheel.main --build dev --repl
    # clojure -m figwheel.main -b dev -r
    # clojure -A:fig -b dev -r
}

prnconf(){
    clojure -m figwheel.main -pc -b dev -r
}

server(){
    clojure -i scripts/server.clj -m figwheel.main -b dev -r
}

"$@"
