#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

clean(){
  rm -rf out .cpcache resources/public/js
}

compile(){
  yarn webpack
}
build(){
  clj -m cljs.main -co build.edn -c
}
run(){
  clj -m cljs.main -w src -co build.edn -ro repl.edn -c  -s "0.0.0.0:3449"
}
repl(){
  clj -m cljs.main -w src  -co build.edn -ro repl.edn -H "0.0.0.0" -p 3449 -c hello-webpack.core  --repl 
}


dev(){
  # https://clojurescript.org/reference/repl-and-main
  build
  run
}
build_advanced(){
  clj -m cljs.main -co build.edn -O advanced -v -c -s
}

help(){
   clj -m cljs.main --help
}

"$@"
