# FROM probe.base1
FROM probe.base2


WORKDIR /opt/app


# COPY package.json deps.edn shadow-cljs.edn ./
# RUN yarn global add shadow-cljs && yarn info
    
EXPOSE 4001 9500 3449 7888 9000


# CMD ["bash","c", "nrepl_clj"]
CMD ["bash","c", "dev"]