#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

clean(){
  rm -rf out .cpcache resources/public/js
}

dev(){
    clj --main cljs.main -co compile-opts.edn -ro repl-opts.edn  --compile hello-world.core --repl 
}

help(){
   clj -m cljs.main --help
}

"$@"
