#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

clean(){
  rm -rf out .cpcache resources/public/js
}

dev(){
  # https://clojurescript.org/reference/repl-and-main
    clj --main cljs.main -co compile-opts.edn -ro repl-opts.edn  --compile hello-world.core --repl #--serve "0.0.0.0:3449"
}

repl(){
  clj -m cljs.main -w src  -co compile-opts.edn -ro repl-opts.edn -H "0.0.0.0" -p 3449 -c hello-world.core  --repl 

}

help(){
   clj -m cljs.main --help
}

allow(){
  sudo chmod -R 757 resources
}

download_cljs_jar(){
  wget https://github.com/clojure/clojurescript/releases/download/r1.10.520/cljs.jar
}

download_cljs_jar_238(){
  wget https://github.com/clojure/clojurescript/releases/download/r1.10.238/cljs.jar
}

build_clj(){
  # java -cp cljs.jar:resources:src clojure.main build.clj
  # java -cp cljs.jar:resources:src cljs.main build.clj 
  java -cp cljs.jar:resources:src clojure.main build.clj

}

jarrepl(){
  # java -cp cljs.jar:resources:src cljs.main jarrepl.clj --repl
  # java -cp cljs.jar clojure.main  -H "0.0.0.0" -p 3449 -c jarrepl.cljs --repl
  # java -cp "cljs.jar;src" cljs.main --compile jarrepl --repl
  java -cp cljs.jar:src cljs.main  -H "0.0.0.0" -p 3449  --compile hello-world.jarrepl --repl
}

serve(){
  clj -m cljs.main -H "0.0.0.0" -p 3449  

}

"$@"
