version: "3.2"

services:

  lab:
    image: probe.lab
    volumes:
      - ../src/edge/lab:/opt/app
      - ../:/opt/probe
      - ../.probedata/shared/src/edge/lab:/opt/shared
    build:
      context: ../src/edge/lab
      dockerfile: ./Dockerfile
    ports:
      - 7800:7878
      - 7080:8080
      # - 7878:7878
      # - 11488:7888
      # - 12083:8080
    command: bash c dev
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    links:
      - base1
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M


  movies:
    image: probe.movies
    volumes:
      - ../src/stable/movies:/opt/app
      - ../:/opt/probe
      - ../.probedata/shared/src/stable/movies:/opt/shared
    build:
      context: ../src/stable/movies
      dockerfile: ./Dockerfile
    ports:
      - 7801:7878
      - 7081:8080
      # - 7878:7878
      # - 11488:7888
      # - 12083:8080
    command: bash c dev
    # command: tail -f /dev/null
    stdin_open: true
    tty: true
    links:
      - base1
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8096M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M

volumes:
  probe.movies.dgraph:
  probe.imdb.postgres:
  probe.stack.postgres: