#!/bin/bash
# PGPASSWORD=postgres

import_sql(){
    gunzip -c ./.data/aligulac.sql.gz | \
    PGPASSWORD=postgres psql -h postgres -p 5432 -d postgres -U postgres 
    #  psql -h postgresdb -p 5432 -d aligulac -c  "CREATE ROLE aligulac"
}

qry(){
     PGPASSWORD=postgres psql -h postgres -p 5432 -d postgresdb -U postgres \
     -c 'SELECT * FROM titles'
}

import(){
     PGPASSWORD=postgres psql -h postgres -p 5432 -d postgresdb -U postgres \
     -c   "COPY titles FROM  
          '/opt/app/.data/imdb/title.basics.tsv'
           DELIMITER E'\t' 
          NULL '\N'  QUOTE E'\b' ESCAPE E'\b' CSV HEADER "

     #\b	U+0008	backspace
}


"$@"
